# Generated by Django 6.0.5 on 2026-06-05 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_category_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_snippets', to=settings.AUTH_USER_MODEL, verbose_name='В избранном у'),
        ),
    ]
